<?
$PERM["/"]["7"]="W";
$PERM["/"]["8"]="W";
$PERM["/"]["*"]="R";
$PERM["index.php"]["G8"]="W";
$PERM["desktop_app"]["*"]="D";
$PERM["video"]["*"]="R";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["8"]="W";
?>